
collisions2:
	g++ collisions2.cpp -I../../engine/include -I../../engine/lib -I/usr/include/python3.8 -L../../engine/bin -I../../engine/lib/freetype-2.10.1/include ../../engine/bin/engine.so  -lpython3.8 -lboost_python38 -fPIC -shared -o collisions2.so